import { Estimate, EstimateExplorerModel } from './models';

export async function getEstimate(): Promise<{ data: EstimateExplorerModel[] }> {
  // Mock data for explorer model
  return Promise.resolve({
    data: [
      {
        ID: 1,
        EstimationNo: 'EST-001',
        Status: 'Open',
        CreatedDate: '2024-06-01T12:00:00Z',
        Description: 'Voyage Estimate for BULK BATAVIA',
        VoyageNo: 'VY-2024-01',
      },
      {
        ID: 2,
        EstimationNo: 'EST-002',
        Status: 'Closed',
        CreatedDate: '2024-06-02T12:00:00Z',
        Description: 'Voyage Estimate for ANOTHER VESSEL',
        VoyageNo: 'VY-2024-02',
      },
    ],
  });
}

export async function getEstimateById(id: number): Promise<Estimate> {
  // Mock data for detail page
  return {
    ID: id,
    EstimationNo: 'EST-1293',
    VesselId: 1,
    CurrencyId: 1,
    CalculationType: 'Voyage',
    Description: 'Voyage Estimate for BULK BATAVIA',
    SpeedBallast: 13.5,
    SpeedLadden: 13.0,
    RunningCost: 100000,
    Status: 'Open',
    VoyageNo: 'VY-2024-01',
    CreatedBy: 'admin',
    CreatedDate: '2024-06-01T12:00:00Z',
    UpdatedBy: 'admin',
    UpdatedDate: '2024-06-01T12:00:00Z',
    Positions: [
      {
        ID: 1,
        EstimateId: id,
        PortId: 1,
        PortTypeId: 1,
        PortCost: 15000,
        CargoCost: 0,
        Distance: 768,
        SecaDistance: 0,
        Speed: 13.5,
        PortDays: 0,
        SteamDays: 0,
        PortDaysSec: 0,
        SteamDaysSec: 0,
        PortDaysAdditionalType: '',
        PortDaysAdditional: 0,
        SteamDaysAdditionalType: '',
        SteamDaysAdditional: 0,
        ArrivalDate: '2022-12-20T08:07:00Z',
        DepatureDate: '2022-12-20T08:07:00Z',
        CreatedBy: 'admin',
        CreatedDate: '2024-06-01T12:00:00Z',
        UpdatedBy: 'admin',
        UpdatedDate: '2024-06-01T12:00:00Z',
      },
      {
        ID: 2,
        EstimateId: id,
        PortId: 2,
        PortTypeId: 2,
        PortCost: 20000,
        CargoCost: 0,
        Distance: 2388,
        SecaDistance: 0,
        Speed: 13.5,
        PortDays: 0,
        SteamDays: 0,
        PortDaysSec: 0,
        SteamDaysSec: 0,
        PortDaysAdditionalType: '',
        PortDaysAdditional: 0,
        SteamDaysAdditionalType: '',
        SteamDaysAdditional: 0,
        ArrivalDate: '2023-01-03T23:19:00Z',
        DepatureDate: '2023-01-09T08:12:00Z',
        CreatedBy: 'admin',
        CreatedDate: '2024-06-01T12:00:00Z',
        UpdatedBy: 'admin',
        UpdatedDate: '2024-06-01T12:00:00Z',
      },
    ],
    Cargoes: [
      {
        ID: 1,
        EstimateId: id,
        SeqNo: 1,
        ChartererId: 1,
        CommodityId: 1,
        Charterer: 'ANGLO',
        Commodity: 'NICKEL',
        Quantity: 73000,
        Rate: 12,
        QuantityTypeId: 1,
        RateTypeId: 1,
        DemurrageRate: 0,
        DespatchRate: 0,
        OtherIncome: 0,
        BunkerCompensation: 0,
        RateCommissionPct: 4,
        DemurrageCommissionPct: 0,
        OtherIncomeCommissionPct: 0,
        BunkerCompCommissionPct: 0,
        Co2Income: 0,
        ToleranceId: 0,
        LoadPorts: 'GRESIK',
        LoadDays: 0,
        LoadPortCost: 0,
        LoadTerm: '',
        LoadTermTypeId: 0,
        LoadExcludePeriodId: 0,
        DischargePorts: 'KRISHNAPATNAM',
        DischargeDays: 0,
        DischargePortCost: 0,
        DischargeTerm: '',
        DischargeTermTypeId: 0,
        DischargeExcludePeriodId: 0,
        BookingId: 0,
        FixtureId: 0,
        CoaId: 0,
        CreatedBy: 'admin',
        CreatedDate: '2024-06-01T12:00:00Z',
        UpdatedBy: 'admin',
        UpdatedDate: '2024-06-01T12:00:00Z',
      },
    ],
    FinanceSummary: [
      {
        ID: 1,
        EstimateId: id,
        SeqNo: 1,
        SummaryTypeId: 1,
        Amount: 875996,
      },
    ],
    Bunkers: [
      {
        ID: 1,
        EstimateId: id,
        GradeId: 1,
        Price: 450,
        PortCons: 2.5,
        BallastCons: 33,
        LaddenCons: 34,
        ROB: 0,
        Co2Emission: 0,
        TotalCons: 370.8,
        TotalCost: 166879.4,
      },
      {
        ID: 2,
        EstimateId: id,
        GradeId: 2,
        Price: 530,
        PortCons: 0,
        BallastCons: 33,
        LaddenCons: 34,
        ROB: 0,
        Co2Emission: 0,
        TotalCons: 0,
        TotalCost: 0,
      },
      {
        ID: 3,
        EstimateId: id,
        GradeId: 3,
        Price: 510,
        PortCons: 1,
        BallastCons: 0.1,
        LaddenCons: 0.1,
        ROB: 0,
        Co2Emission: 0,
        TotalCons: 1,
        TotalCost: 523.5,
      },
    ],
  };
} 